# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.417
    - name: Restore dependencies
      run: dotnet restore CollabApp/CollabApp.Tests/CollabApp.Tests.csproj
    - name: Build
      run: dotnet build CollabApp/CollabApp.Tests/CollabApp.Tests.csproj --no-restore
    - name: Test
      run: dotnet test CollabApp/CollabApp.Tests/CollabApp.Tests.csproj --no-build --verbosity normal
      